package com.littlepants.attack.attackplus.externalModel;

import com.fasterxml.jackson.annotation.JsonProperty;
import lombok.Data;

import java.util.List;
import java.util.Map;

/**
 * @author 厕所歌神李狗蛋
 * @version JAVA17
 * @date 2022/11/24
 * @description
 */
@Data
public class AtomicTests {
    private String name;
    @JsonProperty("auto_generated_guid")
    private String autoGeneratedGuid;
    private String description;
    @JsonProperty("supported_platforms")
    private List<String> supportedPlatforms;
    @JsonProperty("input_arguments")
    private Map<String,InputArgument> inputArguments;
    @JsonProperty("dependency_executor_name")
    private String dependencyExecutorName;
    private List<Dependencies> dependencies;
    private Executor executor;
}
