version: "3"
services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/html:/usr/share/nginx/html
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    privileged: true
  mysql:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=ubuntu
      - MYSQL_DATABASE=attack
    volumes:
      - ./mysql/data/:/var/lib/mysql
      - ./mysql/etc:/etc/mysql/conf.d
      - ./mysql/etc/sql:/docker-entrypoint-initdb.d
  redis:
    image: redis:latest
    command:
      -- requirepass "ubuntu"
    privileged: true
  attack-web:
    image: attack-web:latest
    build: .
    ports:
      - "8384:8384"
    depends_on:
      - mysql
      - redis
    volumes:
      - ./auth_key:/auth_key
      - ./upload:/upload
